### ISSUE TITLE
RegisterVitalRouterDisposable does not work if there are several "LifetimeScope" and only one is unloaded.

### ISSUE THREAD

**Issue by TricksterCat** [hadashiA/VitalRouter#104]
Here is a link to the commit where I am trying to fix this problem. But I think this is not quite the right solution and there is a problem either in VContrainer or in VitalRouter:

https://github.com/TricksterCat/VitalRouter/commit/7c9bd3eed5cde5358690874373834d8586f3d889#diff-e6cf9fb743e76a189b28764332fd80d38ee3967789d078231a9ccfa972d134c9R219

**Comment by hadashiA** [comment]
Ah ok. thanks for the report.

This is probably a VContainer issue. I'm fixing it here now.
https://github.com/hadashiA/VContainer/pull/728

**Comment by hadashiA** [comment]
I've released a fix for the RegisterDisposeCallback in VContainer.
I'd be happy if you could check it out. Thanks.
https://github.com/hadashiA/VContainer/releases/tag/1.16.6

**Comment by TricksterCat** [comment]
Didn't help.

My current approximate scope structure:
1. AppScope
2. SharedScope
2.1 MetaScope
2.2 SharedCoreScope
2.2.1 Core1Scope
2.2.2 Core2Scope

When I load the game, scenes from Scope are loaded sequentially. So, when entering the meta part of the game, the player can go to one of the core minigames. In the process, the scene containing "MetaScope" is unloaded, and first "SharedCoreScope" is loaded, and then "Core1Scope" or "Core2Scope".
But when unloading a scene from "MetaScope", "VitalRouter.VContainer.RoutingDisposable" is not called. But if inside the VitalRouter.VContainer.VContainerExtensions.RegisterVitalRouter method I call "container.Resolve<RoutingDisposable>();" at the end of RegisterBuildCallback, it will work when unloading the scene containing Scope.

**Comment by TricksterCat** [comment]
This fix also works for my case:
```
static void RegisterVitalRouterDisposable(this IContainerBuilder builder, RoutingBuilder routing)
{
    builder.Register(container => new RoutingDisposable(container, routing.MapRoutesInfos), Lifetime.Scoped);
    builder.RegisterBuildCallback(container => container.Resolve<RoutingDisposable>()); //add line
}
```
