### ISSUE TITLE
freelist is not working correct when UnmapRoutes

### ISSUE THREAD

**Issue by HiWill** [hadashiA/VitalRouter#16]
RemoveAt index not set "values[index] = null; "
var span = values.AsSpan(0, lastIndex); should change to var span = values.AsSpan(0, lastIndex+1);

**Comment by hadashiA** [comment]
Yes, so we always need to check for null at loop time.

During traversal,
- After Remove reading the value of the element's reference into the local variable → Target
- Before Remove before reading the value of the element's reference onto the local variable → not Target

Thus, there are differences in when Remove is applied depending on timing, but they are acceptable.

**Comment by hadashiA** [comment]
Ah sorry, I misunderstood.
There seem to be two problems as you pointed out.
I will fix them in #17. Thanks a lot.
