### ISSUE TITLE
Feature 'file-scoped namespace' is not available in C# 9.0

### ISSUE THREAD

**Issue by yashihei** [hadashiA/VitalRouter#4]
Unity 2023.2.4

Hi. I wanted to try out this library right away, so I entered the git URL in the Package Manager to install it. However, I encountered the following error:

`Library\PackageCache\jp.hadashikick.vitalrouter@2176e8ac8b\Runtime\ICommandInterceptor.cs(6,1): error CS8773: Feature 'file-scoped namespace' is not available in C# 9.0. Please use language version 10.0 or greater.`

Currently, to use C# 10 features in Unity, specific settings are required. I thought it would be good to cover this in the documentation, or alternatively, not use file-scoped namespaces.

**Comment by hadashiA** [comment]
@yashihei  Thanks for giving it a try.

I fixed the main branch in #3 and #6 ASAP, so if you don't mind, could you try to re-install it?

I will also create a release with the package version assigned in the near future.

**Comment by yashihei** [comment]
I reinstalled VitalRouter and the error was resolved! Thank you.
