### ISSUE TITLE
Issue with PublishAsync() calls not completing when awaited in nested state.

### ISSUE THREAD

**Issue by setsu323** [hadashiA/VitalRouter#40]
Unity Version: 2022.3.19f
VitalRouter Version: v0.6.4

When awaiting PublishAsync(), if PublishAsync is awaited again within the target On function, that PublishAsync call does not complete.

The issue can be reproduced with the following code:

    private void Start()
    {
        _commandPublisher = Router.Default;
        MapTo(Router.Default);
        
        CallParentCommand();
    }

    public async void CallParentCommand()
    {
        await _commandPublisher.PublishAsync(new ParentCommand());
    }
    
    public async UniTask On(ParentCommand command)
    {
        await _commandPublisher.PublishAsync(new ChildCommand());
    }
    
    public async UniTask On(ChildCommand command)
    {
        await UniTask.Delay(TimeSpan.FromSeconds(1));
    }

When this code is executed, the order of function execution is as follows:

![スクリーンショット 2024-02-04 155124](https://github.com/hadashiA/VitalRouter/assets/32428760/ee443c37-0577-43f3-b727-c3dfbb8fb1b2)

PublishAsync(ChildCommand) does not complete, and instead, PublishAsync(ParentCommand) is the one that completes.

**Comment by hadashiA** [comment]
It seems more like a simple async deadlock than a problem with this library.

Also, in my opinion, in the pub/sub pattern, it is probably best to avoid having the terminating subscriber fire an event immediately, as it causes obfuscation.

You may be able to avoid this problem by stopping the await if possible.

**Comment by setsu323** [comment]
This does not appear to be a simple deadlock issue. A simple deadlock would not explain why PublishAsync(ParentCommand) completes while PublishAsync(ChildCommand) does not.

Additionally, upon further verification, it seems that nesting is not the direct cause. When executing PublishAsync() in sequence as shown below, the task for PublishAsync(FirstCommand) also did not complete.


    public async void CallCommand()
    {
        _commandPublisher.PublishAsync(new FirstCommand()).Forget();
        await UniTask.NextFrame();
        _commandPublisher.PublishAsync(new SecondCommand()).Forget();
    }
    
    public async UniTask On(FirstCommand command)
    {
        await UniTask.Delay(TimeSpan.FromSeconds(2));
    }
    
    public async UniTask On(SecondCommand command)
    {
        await UniTask.Delay(TimeSpan.FromSeconds(1));
    }

![スクリーンショット 2024-02-06 165657](https://github.com/hadashiA/VitalRouter/assets/32428760/af8b5118-429e-40ca-acda-fd6f92363bb3)

**Comment by setsu323** [comment]
Upon further investigation, it seems the issue arises when another PublishAsync task is executed during a PublishAsync task.
The new task seems to complete at the moment the first task is supposed to finish. Moreover, the first task does not complete.

The issue was verified with the following code:

    public async void CallCommand()
    {
        _commandPublisher.PublishAsync(new OneSecondCommand()).Forget();
        await UniTask.NextFrame();
        
        //This will be expected to end after 30 seconds.
        //But this process actually will end after 1 second.
        _commandPublisher.PublishAsync(new ThirtySecondsCommand()).Forget();
    }
    
    public async UniTask On(OneSecondCommand command)
    {
        //Fast process
        await UniTask.Delay(TimeSpan.FromSeconds(1));
    }
    
    public async UniTask On(ThirtySecondsCommand command)
    {
        //Slow process
        await UniTask.Delay(TimeSpan.FromSeconds(30));
    }

**Comment by hadashiA** [comment]
oh sorry, I may have misunderstood. Thank you  for the reproduction code. I'll investigate it.

**Comment by hadashiA** [comment]
Hmm, I tried running your snippet but it doesn't seem to reproduce.
Seems to work as intended.

I'll look into it some more, but if you could provide a reproduction project or stand-alone code that reproduces it, that would be great .

**Comment by setsu323** [comment]
I have published a reproduction project for this issue.
(https://github.com/setsu323/VitalRouterErrorReproduction/tree/master)

Additionally, within this project, I also confirmed the issue where Publish(OneSecondCommand) does not complete.
However, the behavior appears to be somewhat unstable, and occasionally, OneSecondCommand does complete.

**Comment by hadashiA** [comment]
Thank you very much for the reproduction project.

First, I want to clarify what the problem is.

Perhaps your problem is "Pending remains in UniTask Tracker Windows". Am I right?

I have looked into the behavior and it appears that PublishAsync is Complete.

- When awaiting, the next line is executed.
- PublishAsync().ContinueWith(() => ...) .Forget() Then the contintue callback is called.

However, I could confirm that Pending remains in the Tarcker window.
However, this also disappears after waiting for a while and reloading.

I suspect that the library's internal technique of immediately returning UniTasks without awaiting may be affecting the behavior in the Tarcker window.

**Comment by setsu323** [comment]
I see, I understand now.
I never considered that there might be an error in the display of UniTaskTracker itself.
Sorry for the inconvenience caused.

Thank you for identifying the cause. It was very helpful.
