### ISSUE TITLE
[Question] Is this lib complementary to Message Pipe?

### ISSUE THREAD

**Issue by XRSpace-RayWang** [hadashiA/VitalRouter#48]
If the project is using Message Pipe already, using Vital Router along side gains any advantage? Just wondering if they are great to be coexist or use one exclusively will be the best use case.

**Comment by Lowlet** [comment]
Would love to know too

**Comment by hadashiA** [comment]
Hello. Thanks for the question.

Firstly, if you are using MessagePipe, it is probably not worth adding VitalRouter, as MessagePipe is versatile and can handle a variety of in-memory pub/sub patterns. what you can do with VitalRouter, you can do with MessagePipe could be achieved with MessagePipe.

The significance of VitalRouter is twofold

VitalRouter is more opinioneted; MessagePipe can do everything, whereas VitalRouter is more of a feature drop.
I have seen how loosely coupled events have disrupted the control flow in game projects.
If pub/sub is to be introduced into game development, it would be better to have consistent rules.
VitalRouter is intended to lay down those rails.


VitalRouter uses SourceGenerator, and the API design shows the differences arising from that.
As far as my intended use is concerned, the same thing can be described in shorter code.
And SourceGenerator has also brought performance improvements, as Command dispatching is done by Generic Type Caching, which is faster here.
