### ISSUE TITLE
vcontainer integration requires langVersion

### ISSUE THREAD

**Issue by slimshader** [hadashiA/VitalRouter#51]
Docs only mention langVersion setting as  a tip for {init;} props so not sure if this is by design or not but when using VContainer integration results in multiple errors (Unity 2022.3.16):

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8773	Feature 'file-scoped namespace' is not available in C# 9.0. Please use language version 10.0 or greater.	VitalRouter	[...]\Library\PackageCache\jp.hadashikick.vitalrouter@f0088d8968\Runtime\AnonymousInterceptor.cs	5	Active
```

**Comment by hadashiA** [comment]
Hello. Thanks for the report.
The package now contains ccs.rsp. I did not get any errors when I imported VContainer with ViralRouter in a new project.
( btw,  VCntainer does not seem to be involved in your error.

I hope you try the latest version.
