### ISSUE TITLE
Route Attribute is not working

### ISSUE THREAD

**Issue by tahacorbaci** [hadashiA/VitalRouter#56]
Unity 2023.2.14f1
Vital Router v0.9.0

Route attribute exists but source generator is not generating code for it. I guess the source generator dll wasn't updated for 0.9.0 and it's using previous one.

**Comment by hadashiA** [comment]
Thanks for the report.  Fix released [0.9.2](https://github.com/hadashiA/VitalRouter/releases/tag/0.9.2)
