### ISSUE TITLE
Command Pooling problem

### ISSUE THREAD

**Issue by yoyocyhsieh** [hadashiA/VitalRouter#59]
Hi,

When using the `CommandPooling` Interceptor to return to pool automatically, it seems like not return to the corresponding command pool, so always instantiate object when rent from pool.
(The command pool automatically returned is ConcurrentQueueCommandPool<VitalRouter.IPoolableCommand> in my test)

Unity 2022.3.10f1
Vital Router v0.9.2

**Comment by hadashiA** [comment]
Oh. You may be right.  I will check it soon.

**Comment by hadashiA** [comment]
I've released #60. I hope you will check it out. Thanks.

**Comment by yoyocyhsieh** [comment]
Thank you for the fix.
 
I have another question.
Is it ok to use both struct command and class command?
In unity it seems like allocates temporary memory in the following line if command is struct.
`if (command is IPoolableCommand)`

**Comment by yoyocyhsieh** [comment]
> I've released #60. I hope you will check it out. Thanks.

Thank you for the fix.

I have another question.
Is it ok to use both struct command and class command(use the CommandPooling Interceptor)?
In unity it seems like allocates temporary memory(boxing) in the following line if command is struct.
`if (command is IPoolableCommand)`
