### ISSUE TITLE
Another command Pooling problem

### ISSUE THREAD

**Issue by yoyocyhsieh** [hadashiA/VitalRouter#61]
Hi,

Is it ok to use both struct command and class command(and use the CommandPooling Interceptor)?

In unity it seems like allocates temporary memory in the following line if command is struct(boxing?) .
`if (command is IPoolableCommand)`

Unity 2022.3.10f1
Vital Router v0.9.3

**Comment by hadashiA** [comment]
Maybe fixed in #62. I'll release soon.

**Comment by hadashiA** [comment]
Released v0.9.4. If you still have problems, please reopen. Thanks.
