### ISSUE TITLE
VitalRouter is using an unreleased API of VContainer

### ISSUE THREAD

**Issue by yashihei** [hadashiA/VitalRouter#8]
Unity 2023.2.4
VitalRouter v0.2.0

I installed it following the instructions in the VContainer documentation, an error occurred on the VitalRouter side:

`Library\PackageCache\jp.hadashikick.vitalrouter@82aa94a712\Runtime\Unity\VContainerExtensions.cs(83,30): error CS0411: The type arguments for method 'ContainerBuilderUnityExtensions.RegisterComponentOnNewGameObject<T>(IContainerBuilder, Lifetime, string)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`

Upon investigation, I found that the latest release of VContainer (v1.13.2) does not yet support the argument. I resolved the issue by installing without specifying the VContainer version.

https://github.com/hadashiA/VContainer/issues/525

- error
  - "jp.hadashikick.vcontainer": "https://github.com/hadashiA/VContainer.git?path=VContainer/Assets/VContainer#1.13.2" 
- success
  - "jp.hadashikick.vcontainer": "https://github.com/hadashiA/VContainer.git?path=VContainer/Assets/VContainer",

I think a release update on the VContainer side is needed.

**Comment by hadashiA** [comment]
Really appreciate your report. thanks!

I've decided to release [0.14.0](https://github.com/hadashiA/VContainer/releases/tag/1.14.0) of VContainer as soon as possible to address this issue.

You can check it out if you like.
Thanks so much.

**Comment by yashihei** [comment]
I reinstalled the latest release of VContainer and the error was resolved. Thank you.
