### ISSUE TITLE
MapComponent dose not exist

### ISSUE THREAD

**Issue by peyman1959** [hadashiA/VitalRouter#83]
hi
in repository redme in the "Setup with DI" section. the code uses MapComponent . but its dosent exist in RoutingBuilder.
it seemes that Map<T> handle that now. mybe you forgot to update readme?

**Comment by hadashiA** [comment]
Oh.Sorry.  Probably a README mistake. I'll check.

**Comment by hadashiA** [comment]
In #103,  I decided to add MapComponent<>, MapComponentOnNewGameObject<>, and MapEntryPoint<>.
So I think I got what the README says.
Thanks for the report!
