### ISSUE TITLE
Error when using r3 and vitalrouter

### ISSUE THREAD

**Issue by peyman1959** [hadashiA/VitalRouter#84]
i just installed them and got these errors

`Library\PackageCache\jp.hadashikick.vitalrouter@4d807611b2\Runtime\R3Extensions.cs(183,34): error CS0029: Cannot implicitly convert type 'System.Runtime.CompilerServices.ValueTaskAwaiter' to 'Cysharp.Threading.Tasks.UniTask.Awaiter'

Library\PackageCache\jp.hadashikick.vitalrouter@4d807611b2\Runtime\R3Extensions.cs(16,54): error CS1929: 'ValueTask' does not contain a definition for 'Forget' and the best extension method overload 'UniTaskExtensions.Forget(UniTask)' requires a receiver of type 'UniTask'

Library\PackageCache\jp.hadashikick.vitalrouter@4d807611b2\Runtime\R3Extensions.cs(96,9): error CS1929: 'ValueTask' does not contain a definition for 'Forget' and the best extension method overload 'UniTaskExtensions.Forget(UniTask)' requires a receiver of type 'UniTask'

Library\PackageCache\jp.hadashikick.vitalrouter@4d807611b2\Runtime\R3Extensions.cs(269,34): error CS0029: Cannot implicitly convert type 'System.Runtime.CompilerServices.ValueTaskAwaiter' to 'Cysharp.Threading.Tasks.UniTask.Awaiter'`

**Comment by hadashiA** [comment]
Thanks for the report. I've been fixed in #85.
