### ISSUE TITLE
VitalRouter-mruby requires UniTask to be installed even if UniTask is already installed

### ISSUE THREAD

**Issue by hima2nd** [hadashiA/VitalRouter#98]
probably, definition of “VITALROUTER_UNITASK_INTEGRATION” is missing in the versionDefines.

**Comment by hadashiA** [comment]
It seems that the code in VitalRouter.MRuby was partially dependent on UniTask. A learned version has been released. ([1.5.0](https://github.com/hadashiA/VitalRouter/releases/tag/1.5.0)) Thanks for the report.
